=== gosticks/partition-filter-visualization/dataset/benchmark/benchmark.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Benchmark Schema",
  "definitions": {
    "generator": {
      "type": "string",
      "enum": [
        "Sequential",
        "Prime",
        "Random",
        "RandomHuge",
        "RandomHuge2",
        "Skew"
      ]
    },
    "fixture": {
      "type": "string",
      "enum": [
        "Construct",
        "Count",
        "MTCount",
        "Contains",
        "Partitioning",
        "FPR"
      ]
    },
    "visualization": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "enable": {
          "type": "boolean",
          "default": false
        },
        "chart": {
          "type": "string",
          "enum": [
            "line",
            "bar"
          ]
        },
        "x-axis": {
          "type": "string",
          "enum": [
            "k",
            "s",
            "n_partitions",
            "n_threads",
            "n_elements_build",
            "n_elements_lookup",
            "shared_elements"
          ]
        },
        "y-axis": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "time",
              "speedup",
              "throughput",
              "DTLB-misses",
              "ITLB-misses",
              "L1D-misses",
              "L1I-misses",
              "LLC-misses",
              "branch-misses",
              "cycles",
              "instructions",
              "task-clock",
              "avg_size",
              "size",
              "bits",
              "retries",
              "fpr"
            ],
            "default": []
          }
        }
      },
      "if": {
        "properties": {
          "enable": {
            "const": true
          }
        }
      },
      "then": {
        "if": {
          "properties": {
            "chart": {
              "const": "line"
            }
          }
        },
        "then": {
          "required": [
            "x-axis",
            "y-axis"
          ]
        },
        "else": {
          "if": {
            "properties": {
              "chart": {
                "const": "bar"
              }
            }
          },
          "then": {
            "required": [
              "y-axis"
            ]
          }
        },
        "required": [
          "chart"
        ]
      },
      "required": [
        "enable"
      ]
    },
    "optimization": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "Addressing": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "PowerOfTwo",
            "Magic",
            "Lemire",
            "Vacuum",
            "Morton"
          ]
        },
        "Hashing": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Identity",
            "Murmur",
            "Fasthash",
            "Cityhash",
            "TwoIndependentMultiplyShift",
            "SimpleTabulation",
            "Mul"
          ]
        },
        "Partitioning": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Enabled",
            "Disabled"
          ]
        },
        "RegisterSize": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "_32bit",
            "_64bit"
          ]
        },
        "SIMD": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Scalar",
            "AVX2",
            "AVX512"
          ]
        },
        "MultiThreading": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Enabled",
            "Disabled"
          ]
        }
      }
    },
    "parameter": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "k": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer",
            "minimum": 1,
            "maximum": 40
          },
          "minItems": 1
        },
        "s": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer"
          },
          "minItems": 1
        },
        "n_threads": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer",
            "minimum": 1,
            "maximum": 80
          },
          "minItems": 1
        },
        "n_partitions": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer",
            "enum": [
              1,
              2,
              4,
              8,
              16,
              32,
              64,
              128,
              256,
              512,
              1024,
              2048,
              4096,
              8192,
              16384
            ]
          },
          "minItems": 1
        },
        "n_elements": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "oneOf": [
              {
                "type": "number",
                "minimum": 0,
                "maximum": 1000000000
              },
              {
                "type": "object",
                "additionalItems": false,
                "properties": {
                  "build": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1000000000
                  },
                  "lookup": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1000000000
                  },
                  "shared": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 100
                  }
                },
                "required": [
                  "build",
                  "lookup",
                  "shared"
                ]
              }
            ]
          },
          "minItems": 1
        }
      }
    },
    "filter": {
      "type": "object",
      "additionalItems": false,
      "oneOf": [
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "Bloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Naive32",
                "Naive64",
                "Blocked32",
                "Blocked64",
                "Blocked128",
                "Blocked256",
                "Blocked512",
                "Sectorized128",
                "Sectorized256",
                "Sectorized512",
                "Grouped2",
                "Grouped4",
                "Grouped8",
                "Sectorized128Vertical",
                "Sectorized256Vertical",
                "Sectorized512Vertical"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "Xor"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "Fuse"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "Cuckoo"
            },
            "variant": {
              "oneOf": [
                {
                  "type": "string",
                  "enum": [
                    "CuckooOpt",
                    "MortonOpt"
                  ]
                },
                {
                  "type": "string",
                  "pattern": "Standard[2-8]"
                },
                {
                  "type": "string",
                  "pattern": "Morton(2|3|7|15)_[1-9]?[05]_[1-5]?[05]"
                }
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "FastfilterBloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "Branchless"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "FastfilterXor"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "CImplementation",
                "Compressed"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "ImpalaBloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "BSDBloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Naive32",
                "Blocked32",
                "Blocked128",
                "Blocked256",
                "Blocked512",
                "Sectorized128",
                "Sectorized256",
                "Sectorized512",
                "Grouped2",
                "Grouped4",
                "Grouped8",
                "Naive32Batched",
                "Blocked32Batched",
                "Blocked128Batched",
                "Blocked256Batched",
                "Blocked512Batched",
                "Sectorized128Batched",
                "Sectorized256Batched",
                "Sectorized512Batched",
                "Grouped2Batched",
                "Grouped4Batched",
                "Grouped8Batched"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "BSDCuckoo"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard1",
                "Standard2",
                "Standard4",
                "Standard1Batched",
                "Standard2Batched",
                "Standard4Batched"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "EfficientCuckooFilter"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "SemiSorted"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "VacuumFilter"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "SemiSorted"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "AMDMortonFilter"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard1",
                "Standard3",
                "Standard7",
                "Standard15"
              ]
            }
          }
        }
      ]
    },
    "benchmark": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "color": {
          "type": "string",
          "enum": [
            "black",
            "blue",
            "lightblue",
            "green",
            "lightgreen",
            "orange",
            "lightorange",
            "red",
            "lightred"
          ]
        },
        "marker": {
          "type": "string",
          "enum": [
            "circle",
            "triangle",
            "square",
            "diamond"
          ]
        },
        "filter": {
          "$ref": "#/definitions/filter"
        },
        "parameter": {
          "$ref": "#/definitions/parameter"
        },
        "optimization": {
          "$ref": "#/definitions/optimization"
        }
      },
      "required": [
        "name",
        "filter"
      ]
    }
  },
  "type": "object",
  "additionalItems": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "iterations": {
      "type": "integer",
      "minimum": 1,
      "maximum": 1000
    },
    "threads": {
      "type": "integer",
      "minimum": 1,
      "maximum": 1000
    },
    "preprocess": {
      "type": "string",
      "enum": [
        "preprocess_s",
        "preprocess_s_morton",
        "preprocess_n_elements_log",
        "preprocess_s_and_n_elements_log"
      ]
    },
    "generator": {
      "$ref": "#/definitions/generator"
    },
    "fixture": {
      "$ref": "#/definitions/fixture"
    },
    "visualization": {
      "$ref": "#/definitions/visualization"
    },
    "optimization": {
      "allOf": [
        {
          "$ref": "#/definitions/optimization"
        },
        {
          "required": [
            "Addressing",
            "Hashing",
            "Partitioning",
            "RegisterSize",
            "SIMD",
            "EarlyStopping",
            "MultiThreading"
          ]
        }
      ]
    },
    "parameter": {
      "allOf": [
        {
          "$ref": "#/definitions/parameter"
        },
        {
          "required": [
            "k",
            "s",
            "n_threads",
            "n_partitions"
          ]
        }
      ]
    },
    "benchmarks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/benchmark"
      },
      "minItems": 1
    }
  },
  "required": [
    "name",
    "iterations",
    "generator",
    "fixture",
    "visualization",
    "optimization",
    "parameter",
    "benchmarks"
  ]
}

=== gosticks/partition-filter-visualization/dataset/optimization/addressing/addressing_construct.json
{
  "name": "Addressing (Construct)",
  "iterations": 5,
  "preprocess": "preprocess_n_elements_log",
  "fixture": "Construct",
  "generator": "Random",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": [
      8
    ],
    "s": null,
    "n_partitions": [
      1
    ],
    "n_threads": [
      1
    ],
    "n_elements": [
      10,
      5,
      8,
      2,
      100000
    ]
  },
  "optimization": {
    "Addressing": null,
    "Hashing": "Murmur",
    "Partitioning": "Disabled",
    "RegisterSize": "_64bit",
    "SIMD": "Scalar",
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "InitialiseData",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Addressing": "Lemire"
      },
      "parameter": {
        "s": [
          150
        ]
      }
    },
    {
      "name": "BloomBlockedPowerOfTwo",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Addressing": "PowerOfTwo"
      },
      "parameter": {
        "s": [
          150
        ]
      }
    },
    {
      "name": "BloomBlockedMagic",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Addressing": "Magic"
      },
      "parameter": {
        "s": [
          150
        ]
      }
    },
    {
      "name": "BloomBlockedLemire",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Addressing": "Lemire"
      },
      "parameter": {
        "s": [
          150
        ]
      }
    },
    {
      "name": "CuckooPowerOfTwo",
      "filter": {
        "type": "Cuckoo",
        "variant": "CuckooOpt"
      },
      "optimization": {
        "Addressing": "PowerOfTwo"
      },
      "parameter": {
        "s": [
          106
        ]
      }
    },
    {
      "name": "CuckooMagic",
      "filter": {
        "type": "Cuckoo",
        "variant": "CuckooOpt"
      },
      "optimization": {
        "Addressing": "Magic"
      },
      "parameter": {
        "s": [
          106
        ]
      }
    },
    {
      "name": "CuckooLemire",
      "filter": {
        "type": "Cuckoo",
        "variant": "CuckooOpt"
      },
      "optimization": {
        "Addressing": "Lemire"
      },
      "parameter": {
        "s": [
          106
        ]
      }
    },
    {
      "name": "MortonPowerOfTwo",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Addressing": "PowerOfTwo"
      },
      "parameter": {
        "s": [
          138
        ]
      }
    },
    {
      "name": "MortonMagic",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Addressing": "Magic"
      },
      "parameter": {
        "s": [
          138
        ]
      }
    },
    {
      "name": "MortonLemire",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Addressing": "Lemire"
      },
      "parameter": {
        "s": [
          138
        ]
      }
    },
    {
      "name": "XorPowerOfTwo",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Addressing": "PowerOfTwo"
      },
      "parameter": {
        "s": [
          123
        ]
      }
    },
    {
      "name": "XorMagic",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Addressing": "Magic"
      },
      "parameter": {
        "s": [
          123
        ]
      }
    },
    {
      "name": "XorLemire",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Addressing": "Lemire"
      },
      "parameter": {
        "s": [
          123
        ]
      }
    }
  ]
}

=== gosticks/partition-filter-visualization/dataset/perfopt/bloom_blocked.json
{
  "name": "Bloom Blocked (perfopt)",
  "iterations": 5,
  "preprocess": "preprocess_s_and_n_elements_log",
  "fixture": "MTCount",
  "generator": "RandomHuge2",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 ],
    "s": [
      400,
      2600,
      100,
      100,
      2600
    ],
    "n_partitions": [ 32, 64, 128, 256, 512, 1024, 2048, 4096 ],
    "n_threads": [
      10
    ],
    "n_elements": [
      {
        "build": 10,
        "lookup": 10,
        "shared": 10
      },
      {
        "build": 4,
        "lookup": 8,
        "shared": 10
      },
      {
        "build": 8,
        "lookup": 8,
        "shared": 10
      },
      {
        "build": 25,
        "lookup": 0,
        "shared": 10
      },
      {
        "build": 1000,
        "lookup": 100000000,
        "shared": 10
      }
    ]
  },
  "optimization": {
    "Addressing": "Lemire",
    "Hashing": "Murmur",
    "Partitioning": null,
    "RegisterSize": "_64bit",
    "SIMD": "AVX512",
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "Bloom_Blocked64_Nonpart_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked64"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "n_partitions": [ 1 ]
      }
    },
    {
      "name": "Bloom_Blocked64_Part_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked64"
      },
      "optimization": {
        "Partitioning": "Enabled"
      }
    },
    {
      "name": "Bloom_Blocked512_Nonpart_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "n_partitions": [ 1 ]
      }
    },
    {
      "name": "Bloom_Blocked512_Part_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Enabled"
      }
    }
  ]
}

=== gosticks/partition-filter-visualization/dataset/benchmark/paper/introduction/morton_stacked_count.json
{
  "name": "Stacked (Morton, Count)",
  "iterations": 5,
  "fixture": "Count",
  "generator": "Random",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": [
      8
    ],
    "s": [
      138
    ],
    "n_partitions": [
      1
    ],
    "n_threads": [
      1
    ],
    "n_elements": [
      {
        "build": 100000000,
        "lookup": 100000000,
        "shared": 10
      }
    ]
  },
  "optimization": {
    "Addressing": "Lemire",
    "Hashing": "Murmur",
    "Partitioning": null,
    "RegisterSize": "_64bit",
    "SIMD": null,
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "InitialiseData",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "Scalar"
      }
    },
    {
      "name": "Morton_Lemire_Murmur",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "Scalar"
      }
    },
    {
      "name": "Morton_Lemire_Murmur_SIMD",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "AVX512"
      }
    },
    {
      "name": "Morton_Lemire_Murmur_Partitioned",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "Scalar"
      },
      "parameter": {
        "n_partitions": [
          1024
        ]
      }
    },
    {
      "name": "Morton_Lemire_Murmur_SIMD_Partitioned",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "AVX512"
      },
      "parameter": {
        "n_partitions": [
          1024
        ]
      }
    },
    {
      "name": "Morton_Lemire_Murmur_Partitioned_SIMD",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "AVX512"
      },
      "parameter": {
        "n_partitions": [
          1024
        ]
      }
    }
  ]
}

=== gosticks/partition-filter-visualization/dataset/benchmark/paper/background/fingerprintbased/morton7/fingerprintbased_morton7_fpr.json
{
  "name": "Fingerprint-Based FPR (Morton7)",
  "iterations": 100,
  "threads": 48,
  "preprocess": "preprocess_s_morton",
  "fixture": "FPR",
  "generator": "Random",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "execution_time": 1,
    "k": [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25
    ],
    "s": [
      500,
      2500,
      25,
      100,
      200
    ],
    "n_partitions": [
      1
    ],
    "n_threads": [
      1
    ],
    "n_elements": [
      {
        "build": 1000000,
        "lookup": 10000000,
        "shared": 0
      }
    ]
  },
  "optimization": {
    "Addressing": "Magic",
    "Hashing": "Murmur",
    "Partitioning": "Disabled",
    "RegisterSize": "_64bit",
    "SIMD": "Scalar",
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "Morton7_20_5",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_20_5"
      }
    },
    {
      "name": "Morton7_25_5",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_25_5"
      }
    },
    {
      "name": "Morton7_30_5",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_30_5"
      }
    },
    {
      "name": "Morton7_35_5",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_35_5"
      }
    },
    {
      "name": "Morton7_40_5",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_40_5"
      }
    },
    {
      "name": "Morton7_45_5",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_45_5"
      }
    },
    {
      "name": "Morton7_20_10",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_20_10"
      }
    },
    {
      "name": "Morton7_25_10",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_25_10"
      }
    },
    {
      "name": "Morton7_30_10",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_30_10"
      }
    },
    {
      "name": "Morton7_35_10",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_35_10"
      }
    },
    {
      "name": "Morton7_40_10",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_40_10"
      }
    },
    {
      "name": "Morton7_45_10",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_45_10"
      }
    },
    {
      "name": "Morton7_20_15",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_20_15"
      }
    },
    {
      "name": "Morton7_25_15",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_25_15"
      }
    },
    {
      "name": "Morton7_30_15",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_30_15"
      }
    },
    {
      "name": "Morton7_35_15",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_35_15"
      }
    },
    {
      "name": "Morton7_40_15",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_40_15"
      }
    },
    {
      "name": "Morton7_45_15",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_45_15"
      }
    },
    {
      "name": "Morton7_20_20",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_20_20"
      }
    },
    {
      "name": "Morton7_25_20",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_25_20"
      }
    },
    {
      "name": "Morton7_30_20",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_30_20"
      }
    },
    {
      "name": "Morton7_35_20",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_35_20"
      }
    },
    {
      "name": "Morton7_40_20",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_40_20"
      }
    },
    {
      "name": "Morton7_45_20",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_45_20"
      }
    },
    {
      "name": "Morton7_20_25",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_20_25"
      }
    },
    {
      "name": "Morton7_25_25",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_25_25"
      }
    },
    {
      "name": "Morton7_30_25",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_30_25"
      }
    },
    {
      "name": "Morton7_35_25",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_35_25"
      }
    },
    {
      "name": "Morton7_40_25",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_40_25"
      }
    },
    {
      "name": "Morton7_45_25",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_45_25"
      }
    },
    {
      "name": "Morton7_20_30",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_20_30"
      }
    },
    {
      "name": "Morton7_25_30",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_25_30"
      }
    },
    {
      "name": "Morton7_30_30",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_30_30"
      }
    },
    {
      "name": "Morton7_35_30",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_35_30"
      }
    },
    {
      "name": "Morton7_40_30",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_40_30"
      }
    },
    {
      "name": "Morton7_45_30",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_45_30"
      }
    },
    {
      "name": "Morton7_20_35",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_20_35"
      }
    },
    {
      "name": "Morton7_25_35",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_25_35"
      }
    },
    {
      "name": "Morton7_30_35",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_30_35"
      }
    },
    {
      "name": "Morton7_35_35",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_35_35"
      }
    },
    {
      "name": "Morton7_40_35",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_40_35"
      }
    },
    {
      "name": "Morton7_45_35",
      "filter": {
        "type": "Cuckoo",
        "variant": "Morton7_45_35"
      }
    }
  ]
}
