=== gosticks/partition-filter-visualization/dataset/benchmark/benchmark.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Benchmark Schema",
  "definitions": {
    "generator": {
      "type": "string",
      "enum": [
        "Sequential",
        "Prime",
        "Random",
        "RandomHuge",
        "RandomHuge2",
        "Skew"
      ]
    },
    "fixture": {
      "type": "string",
      "enum": [
        "Construct",
        "Count",
        "MTCount",
        "Contains",
        "Partitioning",
        "FPR"
      ]
    },
    "visualization": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "enable": {
          "type": "boolean",
          "default": false
        },
        "chart": {
          "type": "string",
          "enum": [
            "line",
            "bar"
          ]
        },
        "x-axis": {
          "type": "string",
          "enum": [
            "k",
            "s",
            "n_partitions",
            "n_threads",
            "n_elements_build",
            "n_elements_lookup",
            "shared_elements"
          ]
        },
        "y-axis": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "time",
              "speedup",
              "throughput",
              "DTLB-misses",
              "ITLB-misses",
              "L1D-misses",
              "L1I-misses",
              "LLC-misses",
              "branch-misses",
              "cycles",
              "instructions",
              "task-clock",
              "avg_size",
              "size",
              "bits",
              "retries",
              "fpr"
            ],
            "default": []
          }
        }
      },
      "if": {
        "properties": {
          "enable": {
            "const": true
          }
        }
      },
      "then": {
        "if": {
          "properties": {
            "chart": {
              "const": "line"
            }
          }
        },
        "then": {
          "required": [
            "x-axis",
            "y-axis"
          ]
        },
        "else": {
          "if": {
            "properties": {
              "chart": {
                "const": "bar"
              }
            }
          },
          "then": {
            "required": [
              "y-axis"
            ]
          }
        },
        "required": [
          "chart"
        ]
      },
      "required": [
        "enable"
      ]
    },
    "optimization": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "Addressing": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "PowerOfTwo",
            "Magic",
            "Lemire",
            "Vacuum",
            "Morton"
          ]
        },
        "Hashing": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Identity",
            "Murmur",
            "Fasthash",
            "Cityhash",
            "TwoIndependentMultiplyShift",
            "SimpleTabulation",
            "Mul"
          ]
        },
        "Partitioning": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Enabled",
            "Disabled"
          ]
        },
        "RegisterSize": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "_32bit",
            "_64bit"
          ]
        },
        "SIMD": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Scalar",
            "AVX2",
            "AVX512"
          ]
        },
        "MultiThreading": {
          "type": [
            "string",
            "null"
          ],
          "enum": [
            null,
            "Enabled",
            "Disabled"
          ]
        }
      }
    },
    "parameter": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "k": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer",
            "minimum": 1,
            "maximum": 40
          },
          "minItems": 1
        },
        "s": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer"
          },
          "minItems": 1
        },
        "n_threads": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer",
            "minimum": 1,
            "maximum": 80
          },
          "minItems": 1
        },
        "n_partitions": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "integer",
            "enum": [
              1,
              2,
              4,
              8,
              16,
              32,
              64,
              128,
              256,
              512,
              1024,
              2048,
              4096,
              8192,
              16384
            ]
          },
          "minItems": 1
        },
        "n_elements": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "oneOf": [
              {
                "type": "number",
                "minimum": 0,
                "maximum": 1000000000
              },
              {
                "type": "object",
                "additionalItems": false,
                "properties": {
                  "build": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1000000000
                  },
                  "lookup": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1000000000
                  },
                  "shared": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 100
                  }
                },
                "required": [
                  "build",
                  "lookup",
                  "shared"
                ]
              }
            ]
          },
          "minItems": 1
        }
      }
    },
    "filter": {
      "type": "object",
      "additionalItems": false,
      "oneOf": [
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "Bloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Naive32",
                "Naive64",
                "Blocked32",
                "Blocked64",
                "Blocked128",
                "Blocked256",
                "Blocked512",
                "Sectorized128",
                "Sectorized256",
                "Sectorized512",
                "Grouped2",
                "Grouped4",
                "Grouped8",
                "Sectorized128Vertical",
                "Sectorized256Vertical",
                "Sectorized512Vertical"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "Xor"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "Fuse"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "Cuckoo"
            },
            "variant": {
              "oneOf": [
                {
                  "type": "string",
                  "enum": [
                    "CuckooOpt",
                    "MortonOpt"
                  ]
                },
                {
                  "type": "string",
                  "pattern": "Standard[2-8]"
                },
                {
                  "type": "string",
                  "pattern": "Morton(2|3|7|15)_[1-9]?[05]_[1-5]?[05]"
                }
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "FastfilterBloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "Branchless"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "FastfilterXor"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "CImplementation",
                "Compressed"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "ImpalaBloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "BSDBloom"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Naive32",
                "Blocked32",
                "Blocked128",
                "Blocked256",
                "Blocked512",
                "Sectorized128",
                "Sectorized256",
                "Sectorized512",
                "Grouped2",
                "Grouped4",
                "Grouped8",
                "Naive32Batched",
                "Blocked32Batched",
                "Blocked128Batched",
                "Blocked256Batched",
                "Blocked512Batched",
                "Sectorized128Batched",
                "Sectorized256Batched",
                "Sectorized512Batched",
                "Grouped2Batched",
                "Grouped4Batched",
                "Grouped8Batched"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "BSDCuckoo"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard1",
                "Standard2",
                "Standard4",
                "Standard1Batched",
                "Standard2Batched",
                "Standard4Batched"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "EfficientCuckooFilter"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "SemiSorted"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "VacuumFilter"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard",
                "SemiSorted"
              ]
            }
          }
        },
        {
          "properties": {
            "type": {
              "type": "string",
              "const": "AMDMortonFilter"
            },
            "variant": {
              "type": "string",
              "enum": [
                "Standard1",
                "Standard3",
                "Standard7",
                "Standard15"
              ]
            }
          }
        }
      ]
    },
    "benchmark": {
      "type": "object",
      "additionalItems": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "color": {
          "type": "string",
          "enum": [
            "black",
            "blue",
            "lightblue",
            "green",
            "lightgreen",
            "orange",
            "lightorange",
            "red",
            "lightred"
          ]
        },
        "marker": {
          "type": "string",
          "enum": [
            "circle",
            "triangle",
            "square",
            "diamond"
          ]
        },
        "filter": {
          "$ref": "#/definitions/filter"
        },
        "parameter": {
          "$ref": "#/definitions/parameter"
        },
        "optimization": {
          "$ref": "#/definitions/optimization"
        }
      },
      "required": [
        "name",
        "filter"
      ]
    }
  },
  "type": "object",
  "additionalItems": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "iterations": {
      "type": "integer",
      "minimum": 1,
      "maximum": 1000
    },
    "threads": {
      "type": "integer",
      "minimum": 1,
      "maximum": 1000
    },
    "preprocess": {
      "type": "string",
      "enum": [
        "preprocess_s",
        "preprocess_s_morton",
        "preprocess_n_elements_log",
        "preprocess_s_and_n_elements_log"
      ]
    },
    "generator": {
      "$ref": "#/definitions/generator"
    },
    "fixture": {
      "$ref": "#/definitions/fixture"
    },
    "visualization": {
      "$ref": "#/definitions/visualization"
    },
    "optimization": {
      "allOf": [
        {
          "$ref": "#/definitions/optimization"
        },
        {
          "required": [
            "Addressing",
            "Hashing",
            "Partitioning",
            "RegisterSize",
            "SIMD",
            "EarlyStopping",
            "MultiThreading"
          ]
        }
      ]
    },
    "parameter": {
      "allOf": [
        {
          "$ref": "#/definitions/parameter"
        },
        {
          "required": [
            "k",
            "s",
            "n_threads",
            "n_partitions"
          ]
        }
      ]
    },
    "benchmarks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/benchmark"
      },
      "minItems": 1
    }
  },
  "required": [
    "name",
    "iterations",
    "generator",
    "fixture",
    "visualization",
    "optimization",
    "parameter",
    "benchmarks"
  ]
}

=== gosticks/partition-filter-visualization/dataset/optimization/simd/simd_count.json
{
  "name": "SIMD (Count)",
  "iterations": 5,
  "preprocess": "preprocess_n_elements_log",
  "fixture": "Count",
  "generator": "RandomHuge",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": [
      8
    ],
    "s": null,
    "n_partitions": [
      1,
      2,
      4,
      8,
      16,
      32,
      64,
      128,
      256,
      512,
      1024,
      2048,
      4096,
      8192,
      16384
    ],
    "n_threads": [
      1
    ],
    "n_elements": [
      {
        "build": 10,
        "lookup": 10,
        "shared": 10
      },
      {
        "build": 3,
        "lookup": 3,
        "shared": 10
      },
      {
        "build": 9,
        "lookup": 9,
        "shared": 10
      },
      {
        "build": 10,
        "lookup": 10,
        "shared": 10
      },
      {
        "build": 1000,
        "lookup": 100000000,
        "shared": 10
      }
    ]
  },
  "optimization": {
    "Addressing": "Lemire",
    "Hashing": "Murmur",
    "Partitioning": null,
    "RegisterSize": "_64bit",
    "SIMD": "AVX512",
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "InitialiseData",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "s": [
          150
        ],
        "n_partitions": [
          1
        ]
      }
    },
    {
      "name": "BloomBlockedSIMD",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "s": [
          150
        ],
        "n_partitions": [
          1
        ]
      }
    },
    {
      "name": "CuckooSIMD",
      "filter": {
        "type": "Cuckoo",
        "variant": "CuckooOpt"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "s": [
          106
        ],
        "n_partitions": [
          1
        ]
      }
    },
    {
      "name": "MortonSIMD",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "s": [
          138
        ],
        "n_partitions": [
          1
        ]
      }
    },
    {
      "name": "XorSIMD",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "s": [
          123
        ],
        "n_partitions": [
          1
        ]
      }
    },
    {
      "name": "BloomBlockedSIMDPartitioned",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Enabled"
      },
      "parameter": {
        "s": [
          150
        ]
      }
    },
    {
      "name": "CuckooSIMDPartitioned",
      "filter": {
        "type": "Cuckoo",
        "variant": "CuckooOpt"
      },
      "optimization": {
        "Partitioning": "Enabled"
      },
      "parameter": {
        "s": [
          106
        ]
      }
    },
    {
      "name": "MortonSIMDPartitioned",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Enabled"
      },
      "parameter": {
        "s": [
          138
        ]
      }
    },
    {
      "name": "XorSIMDPartitioned",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Enabled"
      },
      "parameter": {
        "s": [
          123
        ]
      }
    }
  ]
}

=== gosticks/partition-filter-visualization/dataset/benchmark/paper/optimization/mt-table/mt_table_construct.json
{
  "name": "MT-Table (Construct)",
  "iterations": 5,
  "fixture": "Construct",
  "generator": "Prime",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": [
      8
    ],
    "s": null,
    "n_partitions": [
      1024
    ],
    "n_threads": [
      10,
      20
    ],
    "n_elements": [
      100000000
    ]
  },
  "optimization": {
    "Addressing": "Lemire",
    "Hashing": "Murmur",
    "Partitioning": null,
    "RegisterSize": "_64bit",
    "SIMD": "Scalar",
    "EarlyStopping": "Disabled",
    "MultiThreading": null
  },
  "benchmarks": [
    {
      "name": "InitialiseData",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "MultiThreading": "Disabled"
      },
      "parameter": {
        "s": [
          150
        ],
        "n_partitions": [
          1
        ],
        "n_threads": [
          1
        ]
      }
    },
    {
      "name": "BloomBlockedPartitioned",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Disabled"
      },
      "parameter": {
        "s": [
          150
        ]
      }
    },
    {
      "name": "CuckooPartitioned",
      "filter": {
        "type": "Cuckoo",
        "variant": "CuckooOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Disabled"
      },
      "parameter": {
        "s": [
          106
        ]
      }
    },
    {
      "name": "MortonPartitioned",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Disabled"
      },
      "parameter": {
        "s": [
          138
        ]
      }
    },
    {
      "name": "XorPartitioned",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Disabled"
      },
      "parameter": {
        "s": [
          123
        ]
      }
    },
    {
      "name": "BloomBlockedPartitionedMT",
      "filter": {
        "type": "Bloom",
        "variant": "Blocked512"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Enabled"
      },
      "parameter": {
        "s": [
          150
        ]
      }
    },
    {
      "name": "CuckooPartitionedMT",
      "filter": {
        "type": "Cuckoo",
        "variant": "CuckooOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Enabled"
      },
      "parameter": {
        "s": [
          106
        ]
      }
    },
    {
      "name": "MortonPartitionedMT",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Enabled"
      },
      "parameter": {
        "s": [
          138
        ]
      }
    },
    {
      "name": "XorPartitionedMT",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "MultiThreading": "Enabled"
      },
      "parameter": {
        "s": [
          123
        ]
      }
    }
  ]
}

=== gosticks/partition-filter-visualization/dataset/benchmark/paper/introduction/xor_stacked_count.json
{
  "name": "Stacked (Xor, Count)",
  "iterations": 5,
  "fixture": "Count",
  "generator": "Random",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": [
      8
    ],
    "s": [
      123
    ],
    "n_partitions": [
      1
    ],
    "n_threads": [
      1
    ],
    "n_elements": [
      {
        "build": 100000000,
        "lookup": 100000000,
        "shared": 10
      }
    ]
  },
  "optimization": {
    "Addressing": "Lemire",
    "Hashing": "Murmur",
    "Partitioning": null,
    "RegisterSize": "_64bit",
    "SIMD": null,
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "InitialiseData",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "Scalar"
      }
    },
    {
      "name": "Xor_Lemire_Murmur",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "Scalar"
      }
    },
    {
      "name": "Xor_Lemire_Murmur_SIMD",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "AVX512"
      }
    },
    {
      "name": "Xor_Lemire_Murmur_Partitioned",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "Scalar"
      },
      "parameter": {
        "n_partitions": [
          1024
        ]
      }
    },
    {
      "name": "Xor_Lemire_Murmur_SIMD_Partitioned",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "AVX512"
      },
      "parameter": {
        "n_partitions": [
          1024
        ]
      }
    },
    {
      "name": "Xor_Lemire_Murmur_Partitioned_SIMD",
      "filter": {
        "type": "Xor",
        "variant": "Standard"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "AVX512"
      },
      "parameter": {
        "n_partitions": [
          1024
        ]
      }
    }
  ]
}

=== gosticks/partition-filter-visualization/dataset/perfopt/bloom_sectorized_vertical.json
{
  "name": "Bloom Sectorized (perfopt)",
  "iterations": 5,
  "preprocess": "preprocess_s_and_n_elements_log",
  "fixture": "MTCount",
  "generator": "RandomHuge2",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": null,
    "s": [
      400,
      2600,
      100,
      100,
      2600
    ],
    "n_partitions": [ 32, 64, 128, 256, 512, 1024, 2048, 4096 ],
    "n_threads": [ 10 ],
    "n_elements": [
      {
        "build": 10,
        "lookup": 10,
        "shared": 10
      },
      {
        "build": 4,
        "lookup": 8,
        "shared": 10
      },
      {
        "build": 8,
        "lookup": 8,
        "shared": 10
      },
      {
        "build": 25,
        "lookup": 0,
        "shared": 10
      },
      {
        "build": 1000,
        "lookup": 100000000,
        "shared": 10
      }
    ]
  },
  "optimization": {
    "Addressing": "Lemire",
    "Hashing": "Murmur",
    "Partitioning": null,
    "RegisterSize": "_64bit",
    "SIMD": "AVX512",
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "Bloom_Sectorized128Vertical_Nonpart_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Sectorized128Vertical"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "AVX512"
      },
      "parameter": {
        "k": [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24 ],
        "n_partitions": [ 1 ]
      }
    },
    {
      "name": "Bloom_Sectorized128Vertical_Part_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Sectorized128Vertical"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "AVX512"
      },
      "parameter": {
        "k": [ 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24 ]
      }
    },
    {
      "name": "Bloom_Sectorized256Vertical_Nonpart_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Sectorized256Vertical"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "k": [ 4, 8, 12, 16, 20, 24 ],
        "n_partitions": [ 1 ]
      }
    },
    {
      "name": "Bloom_Sectorized256Vertical_Part_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Sectorized256Vertical"
      },
      "optimization": {
        "Partitioning": "Enabled"
      },
      "parameter": {
        "k": [ 4, 8, 12, 16, 20, 24 ]
      }
    },
    {
      "name": "Bloom_Sectorized512Vertical_Nonpart_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Sectorized512Vertical"
      },
      "optimization": {
        "Partitioning": "Disabled"
      },
      "parameter": {
        "k": [ 8, 16, 24 ],
        "n_partitions": [ 1 ]
      }
    },
    {
      "name": "Bloom_Sectorized512Vertical_Part_AVX512",
      "filter": {
        "type": "Bloom",
        "variant": "Sectorized512Vertical"
      },
      "optimization": {
        "Partitioning": "Enabled"
      },
      "parameter": {
        "k": [ 8, 16, 24 ]
      }
    }
  ]
}

=== gosticks/partition-filter-visualization/dataset/introduction/morton_stacked_construct.json
{
  "name": "Stacked (Morton, Construct)",
  "iterations": 5,
  "fixture": "Construct",
  "generator": "Random",
  "visualization": {
    "enable": false
  },
  "parameter": {
    "k": [
      8
    ],
    "s": [
      138
    ],
    "n_partitions": [
      1
    ],
    "n_threads": [
      1
    ],
    "n_elements": [
      {
        "build": 100000000,
        "lookup": 1000000000,
        "shared": 10
      }
    ]
  },
  "optimization": {
    "Addressing": "Lemire",
    "Hashing": "Murmur",
    "Partitioning": null,
    "RegisterSize": "_64bit",
    "SIMD": null,
    "EarlyStopping": "Disabled",
    "MultiThreading": "Disabled"
  },
  "benchmarks": [
    {
      "name": "InitialiseData",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "Scalar"
      }
    },
    {
      "name": "Morton_Lemire_Murmur",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Disabled",
        "SIMD": "Scalar"
      }
    },
    {
      "name": "Morton_Lemire_Murmur_Partitioned",
      "filter": {
        "type": "Cuckoo",
        "variant": "MortonOpt"
      },
      "optimization": {
        "Partitioning": "Enabled",
        "SIMD": "Scalar"
      },
      "parameter": {
        "n_partitions": [
          1024
        ]
      }
    }
  ]
}
